### ISSUE TITLE
Minimum sample to embed android

### ISSUE THREAD

**Issue by karino2** [snapscript/snap#1]
I tried to use snapscript in android.

**What I tried 1**
- download snap.jar from http://www.snapscript.org/download.html and put under libs
     - ＞hit 64K method limit and can't build

**What I tried 2**

in build.gradle, add following
```
    implementation group: 'org.snapscript', name: 'snap-all', version: '1.2.1'
```

then try(I use kotlin, but it must be the same as Java)

```
       val model = MapModel(emptyMap<String, Any>())

        val store = ClassPathStore()
        val context = StoreContext(store)
        context.evaluator.evaluate<Any>(model, "3+4")
```

The result is "Could not find import.txt".

What is the correct way to import this jar and use it as interpreter?
(I don't want to add INTERNET permission, so snapd.jar is not what I want, right?)

**Comment by snapscript** [comment]
This should be in the latest jar, looks like it was a build issue.
